export const fallbackWorkbench = {
  metrics: [
    { label: "运行中任务", value: "2", hint: "采集与 AI 任务统一走后台任务中心" },
    { label: "已接入工具", value: "3", hint: "保留抖音采集、AI 视频拆解、AI 提示词反推" },
    { label: "归档内容", value: "128", hint: "AI 拆解与提示词结果可沉淀到素材库" },
    { label: "失败提醒", value: "1", hint: "Cookie 可能需要更新" },
  ],
  tools: [
    {
      id: "douyin-favorites",
      icon: "抖",
      name: "抖音收藏分析器",
      desc: "接入 Douyin_TikTok_Download_API：用户主页、作品详情、收藏视频下载。",
      status: "ready",
      updated: "已预留 API",
      tags: ["视频", "采集", "分析"],
    },
    {
      id: "video-analyzer",
      icon: "影",
      name: "AI 视频拆解",
      desc: "对本地视频做转写、画面描述、关键词和主题归档。",
      status: "ready",
      updated: "今天 17:40",
      tags: ["AI", "素材"],
    },
    {
      id: "prompt-reverse",
      icon: "词",
      name: "AI 提示词反推",
      desc: "从已采集视频反推出可复用的视频生成、图像生成和脚本提示词。",
      status: "ready",
      updated: "今天 18:05",
      tags: ["AI", "提示词"],
    },
  ],
  jobs: [
    {
      id: "job-sync-douyin",
      name: "同步抖音收藏",
      tool: "抖音收藏分析器",
      status: "running",
      progress: 62,
      updated: "18:22",
    },
    {
      id: "job-video-analyze",
      name: "分析本地视频素材",
      tool: "AI 视频拆解",
      status: "running",
      progress: 38,
      updated: "18:18",
    },
    {
      id: "job-cookie-check",
      name: "检查采集 Cookie",
      tool: "抖音收藏分析器",
      status: "error",
      progress: 100,
      updated: "17:55",
    },
  ],
  library: [
    {
      id: "lib-analysis-001",
      title: "AI 视频拆解归档示例",
      type: "拆解归档",
      desc: "自动生成摘要：适合沉淀爆款结构、钩子和脚本公式。",
      tags: ["AI", "拆解"],
    },
    {
      id: "lib-prompt-001",
      title: "AI 提示词反推归档示例",
      type: "提示词归档",
      desc: "沉淀主提示词、负向提示词与镜头分解，方便二次复用。",
      tags: ["AI", "提示词"],
    },
  ],
  integrations: [
    {
      id: "douyin-download-api",
      name: "Douyin_TikTok_Download_API 适配器",
      desc: "仅接入用户主页信息、作品详情、收藏列表视频下载。",
      kind: "python",
      status: "ready",
    },
    {
      id: "ai-prompt-reverse",
      name: "AI 提示词反推适配器",
      desc: "从采集视频创建提示词反推任务，输出 master prompt、negative prompt、分镜提示词和风格关键词。",
      kind: "python",
      status: "ready",
    },
  ],
};
