export const fallbackWorkbench = {
  metrics: [
    { label: "运行中任务", value: "2", hint: "采集和 AI 任务统一收敛到任务中心。" },
    { label: "已接入工具", value: "5", hint: "包含抖音采集、AI 拆解、提示词反推、剪映 SDK 和一句话转素材。" },
    { label: "归档内容", value: "128", hint: "AI 拆解与提示词结果可沉淀到素材库。" },
    { label: "失败提醒", value: "1", hint: "Cookie 或外部服务配置可能需要更新。" },
  ],
  tools: [
    {
      id: "douyin-favorites",
      icon: "抖",
      name: "抖音采集",
      desc: "接入 Douyin_TikTok_Download_API，支持主页、作品详情和收藏下载。",
      status: "ready",
      updated: "已预置 API",
      tags: ["视频", "采集", "分析"],
    },
    {
      id: "video-analyzer",
      icon: "AI",
      name: "AI 视频拆解",
      desc: "对本地或采集视频执行转写、画面分析、钩子拆解和商业结构提炼。",
      status: "ready",
      updated: "今天 17:40",
      tags: ["AI", "素材"],
    },
    {
      id: "prompt-reverse",
      icon: "PR",
      name: "AI 提示词反推",
      desc: "从已采集视频反推可复用的镜头提示词、风格关键词和脚本结构。",
      status: "ready",
      updated: "今天 18:05",
      tags: ["AI", "提示词"],
    },
    {
      id: "jianying-editor-sdk",
      icon: "JY",
      name: "剪映 Editor Skill SDK",
      desc: "暴露 luoluoluo22/jianying-editor-skill 的 SDK 状态、Python 入口和开发指引。",
      status: "ready",
      updated: "本地 SDK",
      tags: ["剪映", "SDK", "自动化"],
    },
    {
      id: "text-to-assets",
      icon: "TA",
      name: "一句话转素材",
      desc: "输入一句方案，AI 自动输出 A-Roll、B-Roll、SFX、BGM 和旁白台词。",
      status: "ready",
      updated: "已接入任务中心",
      tags: ["AI", "素材", "Prompt"],
    },
  ],
  jobs: [
    {
      id: "job-sync-douyin",
      name: "同步抖音收藏",
      tool: "抖音采集",
      status: "running",
      progress: 62,
      updated: "18:22",
    },
    {
      id: "job-video-analyze",
      name: "分析本地视频素材",
      tool: "AI 视频拆解",
      status: "running",
      progress: 38,
      updated: "18:18",
    },
    {
      id: "job-cookie-check",
      name: "检查采集 Cookie",
      tool: "抖音采集",
      status: "error",
      progress: 100,
      updated: "17:55",
    },
  ],
  library: [
    {
      id: "lib-analysis-001",
      title: "AI 视频拆解归档示例",
      type: "拆解归档",
      desc: "自动生成摘要，适合沉淀爆款结构、钩子和脚本公式。",
      tags: ["AI", "拆解"],
    },
    {
      id: "lib-prompt-001",
      title: "AI 提示词反推归档示例",
      type: "提示词归档",
      desc: "沉淀主提示词、负向提示词与镜头拆解，方便二次复用。",
      tags: ["AI", "提示词"],
    },
  ],
  integrations: [
    {
      id: "douyin-download-api",
      name: "Douyin_TikTok_Download_API 适配器",
      desc: "接入用户主页信息、作品详情和收藏列表下载。",
      kind: "python",
      status: "ready",
    },
    {
      id: "ai-prompt-reverse",
      name: "AI 提示词反推适配器",
      desc: "从采集视频创建提示词反推任务，输出 master prompt、negative prompt 和镜头提示词。",
      kind: "python",
      status: "ready",
    },
    {
      id: "jianying-editor-sdk",
      name: "剪映 Editor Skill SDK",
      desc: "本地 SDK 位于 sdks/jianying-editor-skill，提供 JyProject Python API、CLI 和开发指南。",
      kind: "python",
      status: "ready",
    },
  ],
};
